matrix:
  include:
    - language: node_js
      node_js:
        - "7"
      before_script:
        - cd web
      script:
        - npm install && npm run build 
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd api
      script:
        - echo "TODO -- i do not know java"
    - language: docker
      script:
        - docker-compose build

notifications:
  email:
    - jonas@valfridsson.net

branches:
  only:
    - master
    - develop
    - /^feature.*$/
