matrix:
  include:
    - language: node_js
      cache: 
        directories:
          web/node_modules
      node_js:
        - "stable"
      before_script:
        - cd web
      script:
        - npm install && npm run build 
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd api
      script:
        - echo "TODO -- i do not know java"
    - language: docker
      script:
        - docker-compose build
branches:
  only:
    - master
    - develop
    - /^feature.*$/
