###
# Search within postnord
GET https://atapi2.postnord.com/rest/location/v1/surcharge/SE/1124?service_code=31&apikey=59500e5ec56e842319609acdc7f70165
Content-Type: application/json

###
# Search within open street map

GET https://nominatim.openstreetmap.org?format=json&city=Vendels%C3%B6&country=SE
Content-Type: application/json

###
