
database:
  driverClass: org.postgresql.Driver
  user: postnummer
  password: password
  url: jdbc:postgresql://localhost/postnummer?currentSchema=public
  validationQuery: "/* GreatFamily Health Check */ SELECT 1"

logging:
  level: INFO
  loggers:
    se.codeby: DEBUG

postNordClient:
  baseUri: https://atapi2.postnord.com
  apiKey: API_KEY_NEEDED

openStreetMapClient:
  baseUri: https://nominatim.openstreetmap.org
